// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package protos

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// BwEchoClient is the client API for BwEcho service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BwEchoClient interface {
	Echo(ctx context.Context, in *EchoReq, opts ...grpc.CallOption) (*EchoResp, error)
}

type bwEchoClient struct {
	cc grpc.ClientConnInterface
}

func NewBwEchoClient(cc grpc.ClientConnInterface) BwEchoClient {
	return &bwEchoClient{cc}
}

func (c *bwEchoClient) Echo(ctx context.Context, in *EchoReq, opts ...grpc.CallOption) (*EchoResp, error) {
	out := new(EchoResp)
	err := c.cc.Invoke(ctx, "/bwecho.BwEcho/Echo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BwEchoServer is the server API for BwEcho service.
// All implementations must embed UnimplementedBwEchoServer
// for forward compatibility
type BwEchoServer interface {
	Echo(context.Context, *EchoReq) (*EchoResp, error)
	mustEmbedUnimplementedBwEchoServer()
}

// UnimplementedBwEchoServer must be embedded to have forward compatible implementations.
type UnimplementedBwEchoServer struct {
}

func (UnimplementedBwEchoServer) Echo(context.Context, *EchoReq) (*EchoResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Echo not implemented")
}
func (UnimplementedBwEchoServer) mustEmbedUnimplementedBwEchoServer() {}

// UnsafeBwEchoServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BwEchoServer will
// result in compilation errors.
type UnsafeBwEchoServer interface {
	mustEmbedUnimplementedBwEchoServer()
}

func RegisterBwEchoServer(s grpc.ServiceRegistrar, srv BwEchoServer) {
	s.RegisterService(&BwEcho_ServiceDesc, srv)
}

func _BwEcho_Echo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EchoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BwEchoServer).Echo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bwecho.BwEcho/Echo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BwEchoServer).Echo(ctx, req.(*EchoReq))
	}
	return interceptor(ctx, in, info, handler)
}

// BwEcho_ServiceDesc is the grpc.ServiceDesc for BwEcho service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BwEcho_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "bwecho.BwEcho",
	HandlerType: (*BwEchoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Echo",
			Handler:    _BwEcho_Echo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protos/echo.protos",
}
